---
# vars file for docker
    program_list: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    distribution: "{{ 'ubuntu' if ansible_distribution == 'Ubuntu' else 'debian' if ansible_distribution == 'Debian' else 'fedora' if ansible_distribution == 'Fedora' else 'centos' if ansible_distribution == 'CentOS'}}"
    value: "{{ 'dnf-3' if ansible_distribution == 'Fedora' else 'dnf' if ansible_distribution == 'CentOS'}}"
...
