---
# Choosing os_family
    - name: Include OS-specific tasks
      ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
    - name: "Install docker"
      package:
        name: '{{ item }}'
        state: present
      become: true
      loop: '{{  program_list }}'
    - name: "Check status docker's service"
      systemd:
        name: docker
        state: started
        enabled: true
      become: true
...
